function [ type ] = checkPropertyName( name )
%CHECKVARIABLE Checks, if a variable name is valid
%   All variables which should be used in the program have to be defined
%   here.

availableProperties = cellstr(["ELEMENTAL_STIFFNESS", ...
    "OMEGA", ...
    "LAMBDA_S", ...
    "LAMBDA", ...
    "MUE_S", ...
    "MU", ...
    "ETA_S", ...
    "DENSITY_S", ...
    "DENSITY_F", ...
    "ETA_F", ...
    "PRESSURE_0_F", ...
    "HEAT_CAPACITY_RATIO_F", ...
    "PRANDL_NUMBER_F", ...
    "POROSITY", ...
    "TORTUOSITY", ...
    "VISCOUS_CHARACT_LENGTH", ...
    "THERMAL_CHARACT_LENGTH", ...
    "STATIC_FLOW_RESISTIVITY", ...
    "ELEMENTAL_DAMPING", ...
    "ELEMENTAL_MASS", ...
    "IY", ...
    "IZ", ...
    "IT", ...
    "YOUNGS_MODULUS", ...
    "POISSON_RATIO", ...
    "CROSS_SECTION", ...
    "THICKNESS", ...
    "NUMBER_GAUSS_POINT", ... 
    "SHEAR_CORRECTION_FACTOR",...
    "DENSITY", ...
    "STEP", ...
    "RAYLEIGH_ALPHA", ...
    "RAYLEIGH_BETA"]);

available3dProperties = cellstr(["VOLUME_ACCELERATION"]);

availableFlags = cellstr(["FULL_INTEGRATION"]);

if any(ismember(name, availableProperties))
    type = 'variable1d';
elseif any(ismember(name, available3dProperties))
    type = 'variable3d';
elseif any(ismember(name, availableFlags))
    type = 'flag';
else
    error('A property with name \"%s\" has not been defined', name);
end

end

