function [ type ] = checkPropertyName( name )
%CHECKVARIABLE Checks, if a variable name is valid
%   All variables which should be used in the program have to be defined
%   here.

availableProperties = cellstr(["ELEMENTAL_STIFFNESS", ...
    "ELEMENTAL_DAMPING", ...
    "ELEMENTAL_MASS", ...
    "IY", ...
    "IZ", ...
    "IT", ...
    "YOUNGS_MODULUS", ...
    "POISSON_RATIO", ...
    "CROSS_SECTION", ...
    "THICKNESS", ...
    "NUMBER_GAUSS_POINT", ... 
    "SHEAR_CORRECTION_FACTOR",...
    "DENSITY", ...
    "STEP", ...
    "RAYLEIGH_ALPHA", ...
    "DENSITY_SOLID", ...
    "LAMBDA_SOLID", ...
    "MUE_SOLID", ...
    "DAMPING_SOLID", ...
    "DENSITY_FLUID", ...
    "VISCOSITY_FLUID", ...
    "STANDARD_PRESSURE_FLUID", ...
    "HEAT_CAPACITY_FLUID", ...
    "PRANDTL_NUMBER_FLUID", ...
    "POROSITY", ...
    "TORTUOSITY", ...
    "FLOW_RESISTIVITY", ...
    "VISCOUS_LENGHT", ...
    "THERMAL_LENGTH", ...
    "FREQUENCY", ...
    "RAYLEIGH_BETA"]);

available3dProperties = cellstr(["VOLUME_ACCELERATION"]);

availableFlags = cellstr(["FULL_INTEGRATION"]);

if any(ismember(name, availableProperties))
    type = 'variable1d';
elseif any(ismember(name, available3dProperties))
    type = 'variable3d';
elseif any(ismember(name, availableFlags))
    type = 'flag';
else
    error('A property with name \"%s\" has not been defined', name);
end

end

