%
% function [elementList,nodesArrays] = readElements()
%
% Function   : readElements
%
% Description: This function gets the element information from the txt
%              files generated by ANSYS
%
% Parameters :
%
% Return     : elementList                 - matrix with nodal information
%              nodesArrays                 - array with the nodes related
%                                            to certain element
function [elementList,nodesArrays,nodeConnectivity] = readElements()
fid=fopen('DataAnsys/elemNodes.txt') ;                   
fidd=fopen('DataAnsys/elemNodes_modified.dat','w') ; 
if fid < 0, error('Cannot open file'); end 
% Discard some line to read the data from the txt files
for j = 1 : 13
    fgetl(fid) ;                              
end
while ~feof(fid) 
  tline=fgets(fid);  
     if isspace(tline) 
         for j = 1 : 10
             fgetl(fid) ;                     
         end
     else
       fwrite(fidd,tline) ;
     end
end
fclose all ;
filename = 'DataAnsys/elemNodes_modified.dat';
delimiterIn = ' ';
% Get data in matlab
A = importdata(filename,delimiterIn);

nodeConnectivity=A(:,7:end);

A(:,1) = [];
A(:,1) = [];
A(:,2) = [];
A(:,2) = [];
A(:,2) = [];
% Check how many element types there are
elements = unique(A(:,1));
%nodesArrays = cell(length(elements),1);
aux1 = [];
aux2 = [];
nodesArrays = cell(length(elements),1);
for i = 1 : length(elements)
    for j = 1 : size(A,1)
        if A(j,1) == elements(i)
            for k = 2:size(A,2)
                aux1 = [aux1 A(j,k)];
            end
            aux2 = [aux2 aux1];
        end
    end
    nodesArrays(i) = {unique(aux2)};
    aux1 = [];
    aux2 = [];
end

fid=fopen('DataAnsys/elemTyp.txt') ;                   
fidd=fopen('DataAnsys/elemTyp_modified.dat','w') ;     
if fid < 0, error('Cannot open file'); end 
% Discard some line to read the data from the txt files
for j = 1 : 11
    fgetl(fid) ;                              
end

for j = 1 : length(elements)
    tline=fgets(fid);
    fgetl(fid) ;  
    fgetl(fid) ; 
    fgetl(fid) ; 
    fgetl(fid) ;
    fwrite(fidd,tline) ;
end
fclose all ;
filename = 'DataAnsys/elemTyp_modified.dat';
delimiterIn = ' ';
% Get data in matlab
eList = {};
elementList = {};
A = importdata(filename,delimiterIn);
for i =  1:size(A,1)
     eList(i) = textscan(A{i,1},'%s');
     if strcmp(eList{1,i}{1},'ELEMENT')
         elementList{i} = eList{1,i}{5};
     end
end


% [s1,~,~,~] = textread('DataAnsys/elemTyp_modified.dat', '%s %s %s %s');
% elementList = cell(floor(length(s1)/2),1);
% aux = 2;
% for i = 1:length(s1)/2
%     elementList(i) = s1(aux);
%     aux = aux+2;
% end